spring.application.name=2026_0122_SpringbootVisit

#Oracle DataSource
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
# DB url
spring.datasource.username=test
# DB 아이디
spring.datasource.password=test
# DB 패스워드

#View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
# view 호출하면 접두사로 /WEB-INF/views/ 붙여준다는 것
spring.mvc.view.suffix=.jsp
# view 호출하면 접미사로 .jsp 붙여준다는 것